app/urls.py
from django.urls import path, include

from .views import *

app_name = 'app'

urlpatterns = [
    
    path('home', app, name = 'app'),

]

htmx_urlpatterns = [

    path('cp', create_password, name = 'create-password'),
    path('gpi/<uuid:uid>', get_password_info, name = 'get-password-info'),

    path('s', search, name = 'search'),
    path('cs', cancel_search, name = 'cancel-search'),

]

ajax_urlpatterns = [

    path('dp', delete_password, name = 'delete-password'),
    path('up', update_password, name = 'update-password'),

]

urlpatterns += htmx_urlpatterns
urlpatterns += ajax_urlpatterns

web/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {

    'posts': PostSitemap,

}

urlpatterns = [

    path('@dm1n/', admin.site.urls),

    path('', include('user.urls')),
    path('', include('base.urls')),
    path('', include('blog.urls')),
    path('', include('app.urls')),
    path('', include('analytics.urls')),

    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name ='django.contrib.sitemaps.views.sitemap')


] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

app/templates/components/edit-password.html
<div class="wrapper">

    <div id="closeEditPasswordForm">×</div>

    <span id="editPasswordHeading">Изменить пароль</span>

    <div class="new-password-form-wrapper">

        <form>

            <input 
                name="l" 
                type="text" 
                id="editPasswordUID"
                value="{{ password.uid }}" hidden/>

            <input 
                name="l" 
                type="text" 
                id="editPasswordURL" 
                placeholder="Ссылка"
                value="{{ password.url }}" />

            <input 
                name='t' 
                type="text" 
                id="editPasswordName" 
                placeholder="Заголовок"
                value="{{ password.title }}" />

            <input 
                name='u' 
                type="text" 
                id="edit`PasswordLogin" 
                placeholder="Логин"
                value="{{ password.username }}" />

            <input 
                name='p' 
                type="password" 
                id="editPasswordPassword" 
                placeholder="Пароль"
                value="{{ password_password }}" />
            
            <div class="show-password-btn">

                <svg id="shown" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 4.5C5.25 4.5 1.5 9.75 1.5 12s3.75 7.5 10.5 7.5 10.5-5.25 10.5-7.5S18.75 4.5 12 4.5zM5.552 15.103C4.282 13.966 3.5 12.583 3.5 12c0-.584.781-1.966 2.052-3.103C7.231 7.395 9.438 6.5 12 6.5c2.562 0 4.77.895 6.448 2.397 1.27 1.137 2.052 2.52 2.052 3.103 0 .584-.781 1.966-2.052 3.103C16.769 16.605 14.562 17.5 12 17.5c-2.562 0-4.77-.895-6.448-2.397zM12 16a4 4 0 1 1 0-8 4 4 0 0 1 0 8zm2-4a2 2 0 1 1-4 0 2 2 0 0 1 4 0z" /></svg>
                <svg id="hidden" xmlns="http://www.w3.org/2000/svg" width="24" height="24" ><path fill-rule="evenodd" clip-rule="evenodd" d="M20.707 20.707a1 1 0 0 0 0-1.414l-16-16a1 1 0 0 0-1.414 1.414L5.205 6.62C2.785 8.338 1.5 10.683 1.5 12c0 2.25 3.75 7.5 10.5 7.5 1.916 0 3.59-.423 5.006-1.08l2.287 2.287a1 1 0 0 0 1.414 0zm-5.228-3.814-1.774-1.774A4 4 0 0 1 8.38 9.794L6.644 8.058a9.332 9.332 0 0 0-1.09.84C4.28 10.034 3.5 11.417 3.5 12c0 .584.781 1.966 2.052 3.103C7.231 16.605 9.438 17.5 12 17.5a9.97 9.97 0 0 0 3.48-.607zm4.841-.815C21.751 14.61 22.5 13.006 22.5 12c0-2.25-3.75-7.5-10.5-7.5-1.043 0-2.015.125-2.912.346l1.721 1.72c.388-.043.785-.066 1.191-.066 2.562 0 4.77.895 6.448 2.397 1.27 1.137 2.052 2.52 2.052 3.103 0 .51-.596 1.63-1.595 2.663l1.415 1.415z" /></svg>

            </div>

            <textarea 
                name="n" 
                id="editPasswordNote" 
                cols="45" 
                rows="10"
                placeholder="Записка...">{{ password.note }}</textarea>

            <button 
                type="button" 
                id="savePasswordEdit">Сохранить</button>

        </form>

    </div>
    
</div>


<!-- Show/hide password -->

<script>

    $('#hidden').click(function() {

        $(this).hide();
        $('#shown').show();

        $('#editPasswordPassword').attr('type', 'password')
        
    });
    
    $('#shown').click(function() {
        
        $(this).hide();
        $('#hidden').show();

        $('#editPasswordPassword').attr('type', 'text')

    });

</script>

<script>

    /* Create password button disable */

    function checkFormComplete() {

        if ($('#newPasswordPassword').val() && $('#newPasswordLogin').val()) {

            $('#createNewPassword').prop('disabled', false);
            
        } else {
            
            $('#createNewPassword').prop('disabled', true);

        }

    }

    document.addEventListener('keyup', function(e) {

        checkFormComplete();

    });

    /* Edit password request */

    $('#savePasswordEdit').click(function() {
        
        $.ajax({

            'type': 'POST',

            'url': '/up',

            'data': {

                'csrfmiddlewaretoken': '{{ csrf_token }}',

                'i': $('#editPasswordUID').val(),

                'l': $('#editPasswordURL').val(),
                't': $('#editPasswordName').val(),
                'u': $('#editPasswordLogin').val(),
                'p': $('#editPasswordPassword').val(),
                'n': $('#editPasswordNote').val(),

            },
            
        });

    });

    /* Close edit form */

    $('#savePasswordEdit, #closeEditPasswordForm').click(function() {

        btn = $(this);

        btn.addClass('active')

        $('#editPasswordForm').animate({

            'opacity': 0,

        }, 250);

        setTimeout(function() {

            $('#editPasswordForm').hide();
            btn.removeClass('active');

        }, 250);

        });

</script>

app/templates/components/passwords.html
{% load custom_filters %}

{% for password in passwords %}

    <div class="password" hx-get="{% url 'app:get-password-info' password.uid %}" hx-target='#editPasswordForm'>

        <div class="password-info">

            <div class="password-title">{{ password.title }}</div>
            <div class="password-username">{{ password.username }}</div>

        </div>
        
        <div class="password-actions">
            
            <input type="text" id="{{ password.uid }}" class="{{ password.password | remove_b_prefix }}" hidden />
            <input type="text" class='password-url' id="{{ password.url }}"   hidden />
            <div class="password-action copyPassword" title="Скопировать пароль">✂️</div>
            <a href="{{ password.url }}" target="_blank">

                <div class="password-action goToWebsite" title="Перейти на сайт">🌐</div>

            </a>
            <div class="password-action editPassword" title="Править">✏️</div>
            <div class="password-action deletePassword" title="Удалить">🗑️</div>

        </div>

    </div>

{% endfor %}

<script>

    /* Actions on hover */

    $('body').on('mouseover', '.password', function() {

        actions = $(this).children('.password-actions');

        actions.css('display', 'flex');
        actions.animate({

            'opacity': 1,

        }, 250);

    });

    $('body').on('mouseleave', '.password', function() {

        actions = $(this).children('.password-actions');

        actions.animate({

            'opacity': 0,

        }, 250);


        setTimeout(function() {

            actions.hide();

        }, 250);

    });

    /* Btn animation */

    $('.password-action').click(function() {

        btn = $(this);

        btn.addClass('in');

        setTimeout(function() {

            btn.removeClass('in');

        }, 250);

    });

    /* Copy password */

    $('.copyPassword').click(function() {

        password = $(this).siblings('input:first').attr('class');
        copyToClipboard(password);

    });

    /* Edit password init */

    $('.editPassword').click(function() {

        note = $(this).parent().parent();

        $('#editPasswordForm').css('display', 'flex');

        $('#editPasswordForm').animate({

            'opacity': 1,

        }, 250);

        password = $(this).parent().parent()
        uid = password.children('.password-actions').children('input:first').attr('id');

    });

    /* Delete password */

    $('.deletePassword').click(function() {

        uid = $(this).siblings('input:first').attr('id');

        $.ajax({

            type: 'POST',
            
            url: '/dp',

            data: {

                'csrfmiddlewaretoken': "{{ csrf_token }}",
                'i': uid,

            }

    });

    /* Display empty safe if no passwords (only script => 1) */

$   (this).parent().parent().remove();

    if ($('#passwordList').children().length === 1) {

        $('.first-password').css('display', 'flex');

    }}); 

</script>