app/urls.py
from django.urls import path, include

from .views import *

app_name = 'app'

urlpatterns = [
    
    path('home', app, name = 'app'),

]

htmx_urlpatterns = [

    path('cp', create_password, name = 'create-password'),
    path('gpi/<uuid:uid>', get_password_info, name = 'get-password-info'),

    path('s', search, name = 'search'),
    path('cs', cancel_search, name = 'cancel-search'),

]

ajax_urlpatterns = [

    path('dp', delete_password, name = 'delete-password'),
    path('up', update_password, name = 'update-password'),

]

urlpatterns += htmx_urlpatterns
urlpatterns += ajax_urlpatterns

blog/urls.py
from django.urls import path

from .views import *

app_name = 'blog'

urlpatterns = [

    path('blog', blog, name = 'blog'),
    path('blog/<slug:slug>', post, name = 'post'),

]

user/urls.py
from django.urls import path

from django.contrib.auth.views import LogoutView
from .views import *
from .password_recovery_views import *

from django.conf import settings

app_name = 'user'

urlpatterns = [

    # Auth
    path('login/', log_in, name = 'login'),
    path('logout/', log_out, name = 'logout'),
    path('register/', register, name = 'register'),
    path('register/<str:premium_invite_uid>/', invited_register, name = 'invited-register'),

    path('confirm-email/', ce, name = 'ce'), # Email confirmation

    # Password recovery
    path('forgot-password/', forgot_password, name = 'forgot-password'),
    path('recover/', send_recovery_email, name = 'recover'),
    path('reset-password/<uuid:password_recovery_token>/', reset_password, name = 'reset-password'),

    path('toggle-mode/', toggle_mode, name = 'toggle-mode'), # Dark/light

    # Account info
    path('cn/', change_name, name = 'cn'),
    path('cu/', change_username, name = 'cu'),
    path('cp/', change_password, name = 'cp'),

    # Subscription
    path('cancel-sub', cancel_sub, name = 'cancel-sub')

]

web/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {

    'posts': PostSitemap,

}

urlpatterns = [

    path('@dm1n/', admin.site.urls),

    path('', include('user.urls')),
    path('', include('base.urls')),
    path('', include('blog.urls')),
    path('', include('app.urls')),
    path('', include('analytics.urls')),

    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name ='django.contrib.sitemaps.views.sitemap')


] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/models.py
from django.db import models as m

from tinymce.models import HTMLField

from django.urls import reverse

class Post(m.Model):

    title = m.TextField()
    description = m.TextField()
    content = HTMLField()

    slug = m.SlugField(max_length = 60, unique = True)

    thumbnail = m.ImageField(upload_to = 'blog/posts/thumbnails')

    views = m.PositiveSmallIntegerField()

    created_at = m.DateTimeField(auto_now_add = True)
    updated_at = m.DateTimeField(auto_now = True)

    def __str__(self):

        return self.title
    
    class Meta:

        ordering = ['-updated_at']

    def get_absolute_url(self):

        return reverse('blog:post', kwargs={'slug': self.slug})

blog/views.py
from django.shortcuts import render, get_object_or_404

from .models import Post

def blog(request):

    c = {}

    c['user'] = request.user
    c['latest_post'] = Post.objects.latest('created_at')
    c['posts'] = Post.objects.all()

    return render(request, 'blog.html', c)

def post(request, slug):

    post = get_object_or_404(Post, slug = slug)

    c = {}
    c['user'] = request.user
    c['post'] = post

    return render(request, 'post.html', c)

blog/templates/blog.html
{% load static %}
{% load compress %}

<!DOCTYPE html>
<html lang="en">
    <head>

        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        
        <title>Блокнотик | Блог</title>

        <meta name="description" content="Обнаружьте глубины литературного мира через наши статьи. Мы делимся анализами произведений, интересными фактами о писателях и книгах, а также советами по чтению.">
        <meta name="keywords" content="Блокнотик блог, литература, онлайн блокнот, заметки">

        <link rel="icon" type="image/png" href="{% static 'logo.png' %}">

        {% compress css %}
        
            <link rel="stylesheet" href="{% static 'scss/blog/top-nav.scss' %}" type="text/x-scss">
            <link rel="stylesheet" href="{% static 'scss/blog/blog.scss' %}" type="text/x-scss">

        {% endcompress %}

    </head>

    <body>

        <div class="top-nav">

            <div class="brand">

                <a href="/">
            
                    <svg xmlns="http://www.w3.org/2000/svg" width="19.394" height="28.21" viewBox="0 0 19.394 28.21">
                        <path id="Icon_awesome-lightbulb" data-name="Icon awesome-lightbulb" d="M5.293,25.033a1.764,1.764,0,0,0,.3.975l.942,1.415A1.763,1.763,0,0,0,8,28.21h3.4a1.763,1.763,0,0,0,1.468-.787l.942-1.415a1.762,1.762,0,0,0,.3-.975l0-2.113H5.29l0,2.113ZM0,9.7a9.643,9.643,0,0,0,2.4,6.379,15.834,15.834,0,0,1,2.877,5.039c0,.014.006.043.006.043h8.829c0-.014,0-.028.006-.043a15.834,15.834,0,0,1,2.877-5.039A9.7,9.7,0,1,0,0,9.7ZM9.7,5.289A4.413,4.413,0,0,0,5.289,9.7a.882.882,0,0,1-1.763,0A6.178,6.178,0,0,1,9.7,3.526a.882.882,0,0,1,0,1.763Z" transform="translate(0 0)"/>
                    </svg>
                
                    <h1>Блокнотик</h1>
            
                </a>
            
            </div>
            
            <div class="btns">
            
                {% if user.is_authenticated %}
            
                    <a href="/">
            
                        <div class="auth-btn" id="homeBtn">
            
                            <svg class="home" xmlns="http://www.w3.org/2000/svg" width="29.174" height="25.726" viewBox="0 0 29.174 25.726">
                                <path id="Icon_material-home" data-name="Icon material-home" d="M14.192,28.373c1.755-2.106-1.4-6.319,0-8.426a3.286,3.286,0,0,1,5.617,0c1.4,2.106-1.755,6.319,0,8.426s5.266,2.809,7.022,0,0-11.234,0-11.234,6.67,3.16,4.213,0S24.023,4.5,17,4.5,5.416,13.979,2.958,17.139s4.213,0,4.213,0-1.755,8.426,0,11.234S12.437,30.48,14.192,28.373Z" transform="translate(-2.414 -4.5)"/>
                            </svg>
            
                            <span>Дом</span>
            
                        </div>
            
                    </a>
            
                    <a href="{% url 'user:logout' %}">
            
                        <div class="auth-btn" id="logoutBtn">
            
                            <svg class="logout" xmlns="http://www.w3.org/2000/svg" width="28.618" height="27.77" viewBox="0 0 28.618 27.77">
                                <path id="Icon_open-account-logout" data-name="Icon open-account-logout" d="M9.606-1.086c-4,.8-3.2,2.4,0,3.2s9.606-4,12.808,0,3.2,12.007,0,16.01-9.606-.8-12.808,0-4,2.4,0,3.2,12.007,5.6,16.01,0,4-16.81,0-22.414S13.608-1.886,9.606-1.086Zm-3.2,6.4c-1.6.4-6.4,2.4-6.4,4.8s4.8,4.4,6.4,4.8,0-3.2,0-3.2,9.606.8,12.808,0,3.2-2.4,0-3.2S6.4,8.52,6.4,8.52,8,4.918,6.4,5.318Z" transform="translate(0 3.764)"/>
                            </svg>
            
                            <span>Выйти</span>
                        
                        </div>
            
                    </a>
            
                {% else %}
            
                    <a href="{% url 'user:login' %}">
            
                        <div class="auth-btn" id="loginBtn">
            
                            <svg class="login" xmlns="http://www.w3.org/2000/svg" width="29.684" height="26.574" viewBox="0 0 29.684 26.574">
                                <path id="Icon_open-account-login" data-name="Icon open-account-login" d="M8.115-.324c-3.83.766-3.064,2.3,0,3.064s9.192-3.83,12.256,0,3.064,11.49,0,15.321-9.192-.766-12.256,0-3.83,2.3,0,3.064,11.49,5.362,15.321,0,3.83-16.087,0-21.449S11.946-1.09,8.115-.324ZM11.18,5.8c-1.532-.383,0,3.064,0,3.064s-9.192-.766-12.256,0-3.064,2.3,0,3.064,12.256,0,12.256,0-1.532,3.447,0,3.064,8.1-2.193,8.1-4.491S12.712,6.187,11.18,5.8Z" transform="translate(3.375 2.887)"/>
                            </svg>
            
                            <span>Войти</span>
            
                        </div>
            
                    </a>
            
                {% endif %}
            
            </div>                    
            
        </div>
        
        <div class="main">

            <a href="{{ latest_post.get_absolute_url }}">

                <div id="latestPost">

                    <div class="image">
    
                        <img src="{{ latest_post.thumbnail.url }}" alt="Картинка блога">
    
                    </div>
    
                    <div class="text">
    
                        <h1>{{ latest_post.title }}</h1>
                        <h2>{{ latest_post.description }}</h2>
    
                    </div>
    
                </div>

            </a>

            <div class="posts">

                {% for post in posts %}

                    <a href="{{ post.get_absolute_url }}">

                        <div class="post">

                            <div class="image">

                                <img src="{{ post.thumbnail.url }}">

                            </div>

                            <div class="text">

                                <h1>{{ post.title }}</h1>

                            </div>

                        </div>

                    </a>

                {% endfor %}

            </div>

        </div>

    </body>

    <style>

        @font-face {

            font-family: Comfortaa;
            src: url("{% static 'fonts/Comfortaa.ttf' %}");

        }

        body {

            font-family: Comfortaa;

        }

    </style>

</html>

blog/templates/post.html
{% load static %}
{% load compress %}

<!DOCTYPE html>
<html lang="en">
    <head>

        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        
        <title>Блокнотик | Блог</title>

        <meta name="description" content="Обнаружьте глубины литературного мира через наши статьи. Мы делимся анализами произведений, интересными фактами о писателях и книгах, а также советами по чтению.">
        <meta name="keywords" content="Блокнотик блог, литература, онлайн блокнот, заметки">

        <link rel="icon" type="image/png" href="{% static 'logo.png' %}">

        {% compress css %}
        
            <link rel="stylesheet" href="{% static 'scss/blog/top-nav.scss' %}" type="text/x-scss">
            <link rel="stylesheet" href="{% static 'scss/blog/post.scss' %}" type="text/x-scss">

        {% endcompress %}

    </head>

    <body>

        <div class="top-nav">

            <div class="brand">

                <a href="/">
            
                    <svg xmlns="http://www.w3.org/2000/svg" width="19.394" height="28.21" viewBox="0 0 19.394 28.21">
                        <path id="Icon_awesome-lightbulb" data-name="Icon awesome-lightbulb" d="M5.293,25.033a1.764,1.764,0,0,0,.3.975l.942,1.415A1.763,1.763,0,0,0,8,28.21h3.4a1.763,1.763,0,0,0,1.468-.787l.942-1.415a1.762,1.762,0,0,0,.3-.975l0-2.113H5.29l0,2.113ZM0,9.7a9.643,9.643,0,0,0,2.4,6.379,15.834,15.834,0,0,1,2.877,5.039c0,.014.006.043.006.043h8.829c0-.014,0-.028.006-.043a15.834,15.834,0,0,1,2.877-5.039A9.7,9.7,0,1,0,0,9.7ZM9.7,5.289A4.413,4.413,0,0,0,5.289,9.7a.882.882,0,0,1-1.763,0A6.178,6.178,0,0,1,9.7,3.526a.882.882,0,0,1,0,1.763Z" transform="translate(0 0)"/>
                    </svg>
                
                    <h1>Блокнотик</h1>
            
                </a>
            
            </div>
            
            <div class="btns">
            
                {% if user.is_authenticated %}
            
                    <a href="/">
            
                        <div class="auth-btn" id="homeBtn">
            
                            <svg class="home" xmlns="http://www.w3.org/2000/svg" width="29.174" height="25.726" viewBox="0 0 29.174 25.726">
                                <path id="Icon_material-home" data-name="Icon material-home" d="M14.192,28.373c1.755-2.106-1.4-6.319,0-8.426a3.286,3.286,0,0,1,5.617,0c1.4,2.106-1.755,6.319,0,8.426s5.266,2.809,7.022,0,0-11.234,0-11.234,6.67,3.16,4.213,0S24.023,4.5,17,4.5,5.416,13.979,2.958,17.139s4.213,0,4.213,0-1.755,8.426,0,11.234S12.437,30.48,14.192,28.373Z" transform="translate(-2.414 -4.5)"/>
                            </svg>
            
                            <span>Дом</span>
            
                        </div>
            
                    </a>
            
                    <a href="{% url 'user:logout' %}">
            
                        <div class="auth-btn" id="logoutBtn">
            
                            <svg class="logout" xmlns="http://www.w3.org/2000/svg" width="28.618" height="27.77" viewBox="0 0 28.618 27.77">
                                <path id="Icon_open-account-logout" data-name="Icon open-account-logout" d="M9.606-1.086c-4,.8-3.2,2.4,0,3.2s9.606-4,12.808,0,3.2,12.007,0,16.01-9.606-.8-12.808,0-4,2.4,0,3.2,12.007,5.6,16.01,0,4-16.81,0-22.414S13.608-1.886,9.606-1.086Zm-3.2,6.4c-1.6.4-6.4,2.4-6.4,4.8s4.8,4.4,6.4,4.8,0-3.2,0-3.2,9.606.8,12.808,0,3.2-2.4,0-3.2S6.4,8.52,6.4,8.52,8,4.918,6.4,5.318Z" transform="translate(0 3.764)"/>
                            </svg>
            
                            <span>Выйти</span>
                        
                        </div>
            
                    </a>
            
                {% else %}
            
                    <a href="{% url 'user:login' %}">
            
                        <div class="auth-btn" id="loginBtn">
            
                            <svg class="login" xmlns="http://www.w3.org/2000/svg" width="29.684" height="26.574" viewBox="0 0 29.684 26.574">
                                <path id="Icon_open-account-login" data-name="Icon open-account-login" d="M8.115-.324c-3.83.766-3.064,2.3,0,3.064s9.192-3.83,12.256,0,3.064,11.49,0,15.321-9.192-.766-12.256,0-3.83,2.3,0,3.064,11.49,5.362,15.321,0,3.83-16.087,0-21.449S11.946-1.09,8.115-.324ZM11.18,5.8c-1.532-.383,0,3.064,0,3.064s-9.192-.766-12.256,0-3.064,2.3,0,3.064,12.256,0,12.256,0-1.532,3.447,0,3.064,8.1-2.193,8.1-4.491S12.712,6.187,11.18,5.8Z" transform="translate(3.375 2.887)"/>
                            </svg>
            
                            <span>Войти</span>
            
                        </div>
            
                    </a>
            
                {% endif %}
            
            </div>                    
            
        </div>
        
        <div class="main">

            <div class="post">

                <div id="postImage">
    
                    <img src="{{ post.thumbnail.url }}" alt="Картинга блог статьи">
    
                </div>
    
                <div id="postText">
    
                    <h1>{{ post.title }}</h1>
    
                    <div id="content">{{ post.content | safe }}</div>
    
                </div>
    
            </div>

        </div>

    </body>

    <style>

        @font-face {

            font-family: Comfortaa;
            src: url("{% static 'fonts/Comfortaa.ttf' %}");

        }

        body {

            font-family: Comfortaa;

        }

    </style>

</html>