app/urls.py
from django.urls import path, include

from .views import *

app_name = 'app'

urlpatterns = [
    
    path('home', app, name = 'app'),

]

htmx_urlpatterns = [

    path('cp', create_password, name = 'create-password'),
    path('gpi/<uuid:uid>', get_password_info, name = 'get-password-info'),

    path('s', search, name = 'search'),
    path('cs', cancel_search, name = 'cancel-search'),

]

ajax_urlpatterns = [

    path('dp', delete_password, name = 'delete-password'),
    path('up', update_password, name = 'update-password'),

]

urlpatterns += htmx_urlpatterns
urlpatterns += ajax_urlpatterns

base/urls.py
from django.urls import path

from .views import *

app_name = 'base'

urlpatterns = [

    path('', l, name = 'landing'),

    path('contact/', c, name = 'c'),
    path('c/', cs, name = 'cs'), # submit contact form

    path('terms/', t, name = 't'),
    path('privacy/', p, name = 'p'),
    path('juridical-information/', j, name = 'j'),
    
    #path('online-payment-safety/', ops, name = 'ops'),
    #path('data-safety/', ds, name = 'ds'),

]

web/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {

    'posts': PostSitemap,

}

urlpatterns = [

    path('@dm1n/', admin.site.urls),

    path('', include('user.urls')),
    path('', include('base.urls')),
    path('', include('blog.urls')),
    path('', include('app.urls')),
    path('', include('analytics.urls')),

    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name ='django.contrib.sitemaps.views.sitemap')


] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

base/models.py
from django.db import models as m

from django.contrib.auth.models import User
        
class Message(m.Model):
    
    user = m.ForeignKey(User, on_delete = m.CASCADE, blank = True, null = True, related_name = 'message_sender')
    
    name = m.TextField(blank = True)
    email = m.TextField(blank = True)
    
    topic = m.TextField()
    message = m.TextField()
    
    resolved = m.BooleanField(default = False)

    created_at = m.DateTimeField(auto_now_add = True)
    resolved_at = m.DateTimeField(auto_now = True)
    
    class Meta:
        ordering = ['-created_at']

base/views.py
from django.shortcuts import render, HttpResponse

from .models import Message
from analytics.models import Funnel      

import re

# Landing
def l(request):

    c = {}

    c['u'] = request.user

    MOBILE_AGENT_RE=re.compile(r".*(iphone|mobile|androidtouch)",re.IGNORECASE)

    if MOBILE_AGENT_RE.match(request.META['HTTP_USER_AGENT']):
        c['m'] = True
    else:
        c['m'] = False

    return render(request, 'landing.html', c)

# Info
def t(request):
    return render(request, 'info/terms.html', {'u': request.user})

def p(request):
    return render(request, 'info/privacy.html', {'u': request.user})

def j(request):
    return render(request, 'info/juridical.html', {'u': request.user})

# Contact
def c(request):

    c = {}

    c['u'] = request.user

    MOBILE_AGENT_RE=re.compile(r".*(iphone|mobile|androidtouch)",re.IGNORECASE)

    if MOBILE_AGENT_RE.match(request.META['HTTP_USER_AGENT']):
        c['m'] = True
    else:
        c['m'] = False

    return render(request, 'contact.html', c)
    
# contact submit
def cs(request):
    
    if request.user.is_authenticated:
        
        Message.objects.create(
            
            user = request.user,

            topic = request.POST.get('t'),
            message = request.POST.get('m'),
            
        )
        
    else:
        
        Message.objects.create(
            
            name = request.POST.get('n'),
            email = request.POST.get('e'),
            
            topic = request.POST.get('t'),
            message = request.POST.get('m'),

        )
    
    return HttpResponse('K')

base/templates/contact.html
{% load static %}
{% load compress %}

<!DOCTYPE html>

<html lang="ru">

    <head>

        <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <title>Обратная связь | Щиток</title>

        <meta name="description" content="Техническая поддержка Блокнотика. У вас есть вопросы или предложения? Свяжитесь с нами! Мы будем рады помочь.">
        <meta name="keywords" content="блокнотик, обратная связь, блокнот онлайн, онлайн тетрадь, заметки онлайн, блокнот онлайн бесплатно, текстовик, программа для заметок, совместные заметки, голосовой блокнот онлайн, онлайн блокнот для записей">

        <link rel="sitemap" type="application/xml" href="{% static 'sitemap.xml' %}">

        <link rel="icon" type="image/png" href="{% static 'logo.svg' %}">

        {% compress css %}

            <link rel="stylesheet" href="{% static 'scss/base/contact.scss' %}" type="text/x-scss">

        {% endcompress %}

        <script src="{% static 'packages/jquery-3.6.1.min.js' %}"></script>

    </head>

    <body>

        <div class="top-nav">

            <div class="brand">

                <a href="/">
            
                    <svg xmlns="http://www.w3.org/2000/svg" width="19.394" height="28.21" viewBox="0 0 19.394 28.21">
                        <path id="Icon_awesome-lightbulb" data-name="Icon awesome-lightbulb" d="M5.293,25.033a1.764,1.764,0,0,0,.3.975l.942,1.415A1.763,1.763,0,0,0,8,28.21h3.4a1.763,1.763,0,0,0,1.468-.787l.942-1.415a1.762,1.762,0,0,0,.3-.975l0-2.113H5.29l0,2.113ZM0,9.7a9.643,9.643,0,0,0,2.4,6.379,15.834,15.834,0,0,1,2.877,5.039c0,.014.006.043.006.043h8.829c0-.014,0-.028.006-.043a15.834,15.834,0,0,1,2.877-5.039A9.7,9.7,0,1,0,0,9.7ZM9.7,5.289A4.413,4.413,0,0,0,5.289,9.7a.882.882,0,0,1-1.763,0A6.178,6.178,0,0,1,9.7,3.526a.882.882,0,0,1,0,1.763Z" transform="translate(0 0)"/>
                    </svg>
                
                    <h1>Блокнотик</h1>
            
                </a>
            
            </div>
            
            <div class="btns">
            
                {% if request.user.is_authenticated %}
            
                    <a href="/home">
            
                        <div class="auth-btn" id="homeBtn">
            
                            <svg class="home" xmlns="http://www.w3.org/2000/svg" width="29.174" height="25.726" viewBox="0 0 29.174 25.726">
                                <path id="Icon_material-home" data-name="Icon material-home" d="M14.192,28.373c1.755-2.106-1.4-6.319,0-8.426a3.286,3.286,0,0,1,5.617,0c1.4,2.106-1.755,6.319,0,8.426s5.266,2.809,7.022,0,0-11.234,0-11.234,6.67,3.16,4.213,0S24.023,4.5,17,4.5,5.416,13.979,2.958,17.139s4.213,0,4.213,0-1.755,8.426,0,11.234S12.437,30.48,14.192,28.373Z" transform="translate(-2.414 -4.5)"/>
                            </svg>
            
                            <span>Дом</span>
            
                        </div>
            
                    </a>
            
                    <a href="/logout/">
            
                        <div class="auth-btn" id="logoutBtn">
            
                            <svg class="logout" xmlns="http://www.w3.org/2000/svg" width="28.618" height="27.77" viewBox="0 0 28.618 27.77">
                                <path id="Icon_open-account-logout" data-name="Icon open-account-logout" d="M9.606-1.086c-4,.8-3.2,2.4,0,3.2s9.606-4,12.808,0,3.2,12.007,0,16.01-9.606-.8-12.808,0-4,2.4,0,3.2,12.007,5.6,16.01,0,4-16.81,0-22.414S13.608-1.886,9.606-1.086Zm-3.2,6.4c-1.6.4-6.4,2.4-6.4,4.8s4.8,4.4,6.4,4.8,0-3.2,0-3.2,9.606.8,12.808,0,3.2-2.4,0-3.2S6.4,8.52,6.4,8.52,8,4.918,6.4,5.318Z" transform="translate(0 3.764)"/>
                            </svg>
            
                            <span>Выйти</span>
                        
                        </div>
            
                    </a>
            
                {% else %}
            
                    <a href="/login/">
            
                        <div class="auth-btn" id="loginBtn">
            
                            <svg class="login" xmlns="http://www.w3.org/2000/svg" width="29.684" height="26.574" viewBox="0 0 29.684 26.574">
                                <path id="Icon_open-account-login" data-name="Icon open-account-login" d="M8.115-.324c-3.83.766-3.064,2.3,0,3.064s9.192-3.83,12.256,0,3.064,11.49,0,15.321-9.192-.766-12.256,0-3.83,2.3,0,3.064,11.49,5.362,15.321,0,3.83-16.087,0-21.449S11.946-1.09,8.115-.324ZM11.18,5.8c-1.532-.383,0,3.064,0,3.064s-9.192-.766-12.256,0-3.064,2.3,0,3.064,12.256,0,12.256,0-1.532,3.447,0,3.064,8.1-2.193,8.1-4.491S12.712,6.187,11.18,5.8Z" transform="translate(3.375 2.887)"/>
                            </svg>
            
                            <span>Войти</span>
            
                        </div>
            
                    </a>
            
                {% endif %}
            
            </div>                    
            
        </div>
        
        <div class="main">

            <div class="image"><img class='contact-pic' src="{% static 'img/связаться_поддержка_связь_блокнотик.avif' %}" alt="Блокнотик обратная связь связаться/контакты" loading="lazy"></div>

            <div class="text">

                <h1 class="t1">Есть вопросы?</h1>
                <h1 class="t2">Будем рады помочь!</h1>

                {% if n %}

                    <p>{{n}}, заполните эту форму и мы свяжемся с вами как можно скорее 🙂</p>

                {% else %}

                    <p>Заполните эту форму и мы свяжемся с вами как можно скорее 🙂</p>

                {% endif %}

            </div>

            <div class="form">

                <div class="fields">

                    {% if not user.is_authenticated %}

                        <input 
                            type="text"
                            placeholder="Имя"
                            id="name" />

                        <input 
                            type="email"
                            placeholder="Электронная почта"
                            id="email"
                            autocomplete="on" />

                    {% endif %}

                    <select id="questionTheme">
                        <option value="Без темы">—Тема вопроса—</option>
                        <option value="Вопрос">Вопрос</option>
                        <option value="Ошибка">Ошибка</option>
                        <option value="Идея по улучшению">Идея по улучшению приложения</option>
                        <option value="Коммерческое предложение">Коммерческое предложение</option>
                    </select>

                    <textarea 
                        type="text"
                        placeholder="Сообщение"
                        id="message"></textarea>

                    <button 
                        type="button"
                        id="submitForm"
                        disabled>Отправить</button>

                </div>

            </div>

            <div class="message-submitted">

                <h1>Спасибо, что связались с нами!</h1>

                <p>Мы ответим вам в течении 24 часов.</p>

            </div>

            <div class="bottom-nav">
                    
                <div class="links">
                
                   <ul>

                        <li>
                    
                            <a href="/">
                
                                <h4 class='copyright'>©<i>Блокнотик 2024</i></h4>
                
                            </a>
                
                        </li>
                
                       <li>

                            <a href="/terms" class="link" target="_blank">
                    
                                Информация
                
                            </a>
                
                           <a href="#" class="link" target="_blank">
                
                               Обратная связь
                
                           </a>

                           
                           <a href="/blog" class="link" target="_blank">
                
                                Блог
             
                            </a>
                
                       </li>
                
                   </ul>
                
                </div>

            </div>

        </div>

    </body>

    <style>

        @font-face {
            font-family: Comfortaa;
            src: url("{% static 'fonts/Comfortaa.ttf' %}");
        }

        body {

            font-family: Comfortaa;

        }

        .link {

            margin-right: 30px;

        }

    </style>

    <!-- Nav btns -->

    <script>
    
        $('.auth-btn').click(function() {

            btn = $(this);

            btn.addClass('in');

            setTimeout(function() {

                btn.removeClass('in');

            }, 250);

        });

    </script>

    <!-- Submit btn disable -->

    {% if not user.is_authenticated %}

        <script>

            function disableBtn() {

            if ($('#message').val() && $('#name').val() && $('#email').val()) {

                $('#submitForm').prop('disabled', false);
                
            } else {
                
                $('#submitForm').prop('disabled', true);

            }

            }

            $("#message").on('input', function() {

                disableBtn();

            });

            document.getElementById('name').addEventListener('input', function() {

                disableBtn();

            });

            document.getElementById('email').addEventListener('input', function() {

                disableBtn();

            });

        </script>

    {% else %}

        <script>

            function disableBtn() {

                if ($('#message').val()) {

                    $('#submitForm').prop('disabled', false);
                    
                } else {
                    
                    $('#submitForm').prop('disabled', true);

                }

            }

            $("#message").on('input', function() {

                disableBtn();

            });

        </script>

    {% endif %}
    <script>

        

    </script>

    <!-- Form submission btn script -->

    <script>

        $('#submitForm').click(function() {

            $('.form, .text').animate({

                'opacity': 0,

            }, 500);

            setTimeout(function() {

                $('.form').hide();
                $('.text').hide();
                $('.message-submitted').show();
                $('.message-submitted').animate({

                    'opacity': 1,

                }, 500);

            }, 500);

        });

    </script>

    {% if user.is_authenticated %}

        <script>

            $('#submitForm').click(function() {
        
                $('#submitForm').addClass('in');
                setTimeout(function() {
        
                    $('#submitForm').removeClass('in');
        
                }, 250);
        
                $.ajax({
        
                    type: 'POST',
        
                    url: "{% url 'base:cs' %}",
        
                    data: {
        
                        'csrfmiddlewaretoken': '{{csrf_token}}',
        
                        't': $('#questionTheme').val(),
                        'm': $('#message').val(),
        
                    }
        
                });
        
            });

        </script>

    {% else %}

        <script>

            $('#submitForm').click(function() {
    
                $('#submitForm').addClass('in');
                setTimeout(function() {
    
                    $('#submitForm').removeClass('in');
    
                }, 250);

                $.ajax({
    
                    type: 'POST',
    
                    url: "{% url 'base:cs' %}",
    
                    data: {
    
                        'csrfmiddlewaretoken': '{{csrf_token}}',
    
                        'n': $('#name').val(),
                        'e': $('#email').val(),
    
                        't': $('#questionTheme').val(),
                        'm': $('#message').val(),
    
                    }
    
                });
    
            });

        </script>

    {% endif %}

</html>